version: '3.7'

services:
  frontend:
    container_name: Frontend
    build: Frontend/.
    ports:
      - "5173:5173"
    depends_on:
      - backend

  backend:
    container_name: Backend
    build: Backend/.
    environment:
      DATABASE_HOST: db  
      DATABASE_USERNAME: root  
      DATABASE_PASSWORD: root  
      DATABASE_PORT: 3306  
      DATABASE_NAME: pokeapi_development

    networks:
      - my_network
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: ["sh", "-c","rails db:migrate && rails s -b 0.0.0.0"]

  db:
    container_name: Banco
    build: Banco/.
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pokeapi_development
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    networks:
      - my_network
    ports:
      - "3306:3306"
      
networks:
  my_network:
    driver: bridge
   
