version: '3'

services:
  frontend:
    container_name: Frontend
    build: Frontend/.
    ports:
      - "5173:5173"
    depends_on:
      - backend

  backend:
    container_name: Backend
    build: Backend/.
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    container_name: Banco
    image: nouchka/sqlite3:latest
    environment:
      - SQLITE_DB_PATH="Backend/pokeapi_development"
