name: Deploy para Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      VERCEL_ORG_ID: ${{secrets.ORG_ID}}
      VERCEL_PROJECT_ID: ${{secrets.PROJECT_ID}}

    steps:
      - name: Olhando o Código
        uses: actions/checkout@v3

      - name: Instalando Vercel CLI
        working-directory: ./Frontend
        run: npm install --global vercel

      - name: Vercel Pull Informação 
        working-directory: ./Frontend
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
        
      - name: Build Vercel
        working-directory: ./Frontend
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy
        working-directory: ./Frontend
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
        
        
