name: Deploy para Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Olhando o Código
        uses: actions/checkout@v3
        
      - name: Diretório do Frontend
        uses: ./Frontend

      - name: Instalando Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Instalando Dependências
        run: npm install

      - name: Building a aplicação
        run: npm run build 
        
      - name: Deploy Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          npm install -g vercel
          vercel deploy --prod --confirm --token=$VERCEL_TOKEN --scope=$VERCEL_ORG_ID --project-id=$VERCEL_PROJECT_ID
